server:
  port: 8080
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: citrusgo54@gmail.com
    password: uavepzrnsahgzpij
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true